OANDA_API_KEY = "c934bb8699bd3ec60e58b918a3d5399b-27034ab74bc7b6a1f2546817767e57d3"
OANDA_ACCOUNT_ID = "101-002-37205058-001"
OANDA_ENV = "practice"
ACCESS_TOKEN = st.secrets["OANDA_API_KEY"]
ACCOUNT_ID = st.secrets["OANDA_ACCOUNT_ID"]
client = API(access_token=ACCESS_TOKEN, environment=st.secrets["OANDA_ENV"])
